# Generated by Django 4.2.7 on 2023-11-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessages',
            options={'verbose_name_plural': 'Conversation Messages'},
        ),
    ]
